# Generated by Django 4.1 on 2023-10-08 23:33

import birthday.fields
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofile',
            name='date_of_birth',
            field=birthday.fields.BirthdayField(default='1991-08-02'),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
