# Generated by Django 4.1 on 2023-10-09 19:13

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofile',
            name='date_of_birth_dayofyear_internal',
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='customprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
