# Generated by Django 4.1 on 2023-10-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customprofile_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
