# Generated by Django 4.1 on 2023-11-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_favorites'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'ordering': ['user'], 'verbose_name': 'Saved Item', 'verbose_name_plural': 'Saved Items'},
        ),
        migrations.RenameField(
            model_name='favorites',
            old_name='favorites',
            new_name='items',
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['user'], name='users_favor_user_id_1fd5ef_idx'),
        ),
    ]
