# Generated by Django 4.1 on 2023-11-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_favorites_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='saved_items', to='shop.product'),
        ),
    ]
