# Generated by Django 4.1 on 2023-11-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_review_review_shop_review_created_0f62c3_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
