# Generated by Django 4.1 on 2023-11-21 21:12

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[orders.models.postal_code_validator]),
        ),
    ]
