# Generated by Django 4.1 on 2023-11-21 21:54

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, null=True, validators=[orders.models.postal_code_validator]),
        ),
    ]
