# Generated by Django 4.1 on 2023-11-22 20:20

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, validators=[orders.models.postal_code_validator]),
        ),
    ]
