# Generated by Django 4.1 on 2024-03-12 00:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_uuid_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50),
        ),
    ]
